apiVersion: v2
name: nodepulse
description: A plug-and-play observability stack for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/DARK-art108/nodepulse
sources:
  - https://github.com/DARK-art108/nodepulse
maintainers:
  - name: Ritesh Yadav
    email: daydreamingguy941@gmail.com
keywords:
  - monitoring
  - prometheus
  - grafana
  - security
  - kubernetes
  - metrics
  - alerting
  - vulnerability
  - scanning
annotations:
  artifacthub.io/changes: |
    - Initial release
  artifacthub.io/images: |
    - name: prometheus
      image: prom/prometheus:v2.45.0
    - name: grafana
      image: grafana/grafana:9.5.3
    - name: trivy-operator
      image: aquasec/trivy-operator:0.25.0
dependencies:
  - name: prometheus
    version: 25.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 7.1.0
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: trivy-operator
    version: 0.25.0
    repository: https://aquasecurity.github.io/helm-charts
    condition: trivy.enabled 