# Default values for nodepulse.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global settings
global:
  # Enable or disable all components
  enabled: true
  # Set the default storage class
  storageClass: standard
  # Set the default image pull policy
  imagePullPolicy: IfNotPresent
  # Set the default image registry
  imageRegistry: ""
  # Set the default image tag
  imageTag: ""

# Prometheus configuration
prometheus:
  enabled: true
  server:
    persistentVolume:
      size: 10Gi
    retention: 5d
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 500m
  alertmanager:
    enabled: true
    persistentVolume:
      size: 2Gi
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m
  pushgateway:
    enabled: true
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m
  kubeStateMetrics:
    enabled: true
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m
  nodeExporter:
    enabled: false

# Grafana configuration
grafana:
  enabled: true
  adminPassword: admin
  persistence:
    enabled: true
    size: 5Gi
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 100m
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.monitoring.svc.cluster.local
          access: proxy
          isDefault: true

# Trivy Operator configuration
trivy:
  enabled: true
  resources:
    requests:
      memory: 256Mi
      cpu: 50m
    limits:
      memory: 512Mi
      cpu: 100m
  vulnerabilityScanner:
    enabled: true
    schedule: "0 0 * * *"
  concurrentScanJobsLimit: 2

# Disabled components
metrics-server:
  enabled: false

loki:
  enabled: false

opentelemetry-collector:
  enabled: false 